-- SiFaskes full SQL bootstrap
-- Generated by Codex

CREATE DATABASE IF NOT EXISTS sifaskes CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sifaskes;

DROP TABLE IF EXISTS access_tokens;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS facilities;

CREATE TABLE facilities (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(190) NOT NULL UNIQUE,
    name VARCHAR(190) NOT NULL,
    type ENUM('RSAU BLU', 'RSAU PNBP', 'FKTP') NOT NULL,
    jajaran VARCHAR(100) NULL,
    address TEXT NULL,
    latitude DECIMAL(10,7) NULL,
    longitude DECIMAL(10,7) NULL,
    is_coordinate_estimated TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    facility_id INT UNSIGNED NULL,
    username VARCHAR(64) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('admin_pusat', 'rs_admin', 'user_rs') NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_facility
      FOREIGN KEY (facility_id) REFERENCES facilities(id)
      ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE access_tokens (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    token CHAR(64) NOT NULL UNIQUE,
    expires_at DATETIME NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tokens_user
      FOREIGN KEY (user_id) REFERENCES users(id)
      ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX idx_access_tokens_user_id (user_id),
    INDEX idx_access_tokens_expires_at (expires_at)
);

USE sifaskes;

-- Seed fasilitas utama (RSAU BLU, RSAU PNBP, FKTP)
INSERT INTO facilities (code, name, type, jajaran, is_coordinate_estimated) VALUES
('rsgm-drg-r-poerwanto-rsgm-drg-k-aryadhi', 'RSGM drg. R. Poerwanto / RSGM drg. K. Aryadhi', 'RSAU PNBP', 'Laknis Mabesau', 1),
('rsau-dr-m-hassan-toto-lanud-ats', 'RSAU dr. M. Hassan Toto Lanud Ats', 'RSAU PNBP', 'Kodau I', 1),
('rsau-dr-abdul-malik-lanud-soewondo', 'RSAU dr. Abdul Malik Lanud Soewondo', 'RSAU PNBP', 'Kodau I', 1),
('rsau-dr-sukirman-lanud-roesmin-nurjadin', 'RSAU dr. Sukirman Lanud Roesmin Nurjadin', 'RSAU PNBP', 'Kodau I', 1),
('rsau-dr-m-sutomo-lanud-sutomo', 'RSAU dr. M. Sutomo Lanud Sutomo', 'RSAU PNBP', 'Kodau I', 1),
('rsau-dr-hoediyono-lanud-suryadarma', 'RSAU dr. Hoediyono Lanud Suryadarma', 'RSAU PNBP', 'Kodau I', 1),
('rsau-dr-yuniati-wisma-karyani-lanud-raden-sadjad', 'RSAU dr. Yuniati Wisma Karyani Lanud Raden Sadjad', 'RSAU PNBP', 'Kodau I', 1),
('rsau-dr-dody-sardjoto-lanud-sultan-hasanuddin', 'RSAU dr. Dody Sardjoto Lanud Sultan Hasanuddin', 'RSAU PNBP', 'Kodau II', 1),
('rsau-lanud-samsudin-noor', 'RSAU Lanud Samsudin Noor', 'RSAU PNBP', 'Kodau II', 1),
('rsau-dr-erham-harsana-lanud-iswahjudi', 'RSAU dr. Erham Harsana Lanud Iswahjudi', 'RSAU PNBP', 'Kodau II', 1),
('rsau-dr-soemitro-lanud-muljono', 'RSAU dr. Soemitro Lanud Muljono', 'RSAU PNBP', 'Kodau II', 1),
('rsau-dr-m-moenir-lanud-abd-saleh', 'RSAU dr. M. Moenir Lanud Abd. Saleh', 'RSAU PNBP', 'Kodau II', 1),
('rumkit-lanud-dhomber', 'Rumkit Lanud Dhomber', 'RSAU PNBP', 'Kodau II', 1),
('rsau-dr-charles-p-j-south-lanud-samratulangi', 'RSAU dr. Charles P. J. South Lanud Samratulangi', 'RSAU PNBP', 'Kodau II', 1),
('rumkit-lanud-eltari', 'Rumkit Lanud Eltari', 'RSAU PNBP', 'Kodau II', 1),
('rsau-dr-kresno-lanud-manuhua', 'RSAU dr. Kresno Lanud Manuhua', 'RSAU PNBP', 'Kodau III', 1),
('rumkit-lanud-silas-papare', 'Rumkit Lanud Silas Papare', 'RSAU PNBP', 'Kodau III', 1),
('rsau-dr-siswanto-lanud-adi-soemarmo', 'RSAU dr. Siswanto Lanud Adi Soemarmo', 'RSAU PNBP', 'Kodiklatau', 1),
('rsau-dr-norman-t-lubis-lanud-sulaiman', 'RSAU dr. Norman T. Lubis Lanud Sulaiman', 'RSAU PNBP', 'Kodiklatau', 1),
('rspau-dr-s-hardjolukito', 'RSPAU dr. S. Hardjolukito', 'RSAU BLU', 'Kodiklatau', 1),
('rsau-dr-e-antariksa', 'RSAU dr. E. Antariksa', 'RSAU BLU', 'Balakpus', 1),
('rsau-dr-m-salamun', 'RSAU dr. M. Salamun', 'RSAU BLU', 'Balakpus', 1),
('fktp-denma-koopsudnas', 'FKTP Denma Koopsudnas', 'FKTP', 'Koopsudnas', 1),
('fktp-kosek-i-medan', 'FKTP Kosek I Medan', 'FKTP', 'Kodau I', 1),
('fktp-denma-kodau-i', 'FKTP Denma Kodau I', 'FKTP', 'Kodau I', 1),
('fktp-lanud-atang-sendjaja', 'FKTP Lanud Atang Sendjaja', 'FKTP', 'Kodau I', 1),
('fktp-lanud-roesmin-nurjadin', 'FKTP Lanud Roesmin Nurjadin', 'FKTP', 'Kodau I', 1),
('fktp-lanud-supadio-ambara-asasta', 'FKTP Lanud Supadio / Ambara Asasta', 'FKTP', 'Kodau I', 1),
('fktp-lanud-s-suryadarma-angkasa', 'FKTP Lanud S. Suryadarma / Angkasa', 'FKTP', 'Kodau I', 1),
('fktp-lanud-husein-sastranegara', 'FKTP Lanud Husein Sastranegara', 'FKTP', 'Kodau I', 1),
('fktp-lanud-soewondo-flaminggo', 'FKTP Lanud Soewondo / Flaminggo', 'FKTP', 'Kodau I', 1),
('fktp-lanud-sultan-iskandar-muda', 'FKTP Lanud Sultan Iskandar Muda', 'FKTP', 'Kodau I', 1),
('fktp-lanud-raden-sadjad', 'FKTP Lanud Raden Sadjad', 'FKTP', 'Kodau I', 1),
('fktp-lanud-sri-mulyono-herlambang', 'FKTP Lanud Sri Mulyono Herlambang', 'FKTP', 'Kodau I', 1),
('fktp-lanud-sutan-sjahrir', 'FKTP Lanud Sutan Sjahrir', 'FKTP', 'Kodau I', 1),
('fktp-lanud-raja-haji-fisabilillah', 'FKTP Lanud Raja Haji Fisabilillah', 'FKTP', 'Kodau I', 1),
('fktp-lanud-maimun-saleh', 'FKTP Lanud Maimun Saleh', 'FKTP', 'Kodau I', 1),
('fktp-lanud-h-a-s-hanandjoeddin', 'FKTP Lanud H.A.S. Hanandjoeddin', 'FKTP', 'Kodau I', 1),
('fktp-lanud-wiriadinata', 'FKTP Lanud Wiriadinata', 'FKTP', 'Kodau I', 1),
('fktp-lanud-pangeran-m-bun-yamin', 'FKTP Lanud Pangeran M. Bun Yamin', 'FKTP', 'Kodau I', 1),
('fktp-lanud-harry-hadisoemantri', 'FKTP Lanud Harry Hadisoemantri', 'FKTP', 'Kodau I', 1),
('fktp-lanud-sugiri-sukani', 'FKTP Lanud Sugiri Sukani', 'FKTP', 'Kodau I', 1),
('fktp-lanud-iskandar', 'FKTP Lanud Iskandar', 'FKTP', 'Kodau I', 1),
('fktp-kosek-ii-makassar', 'FKTP Kosek II Makassar', 'FKTP', 'Kodau II', 1),
('fktp-denma-kodau-ii', 'FKTP Denma Kodau II', 'FKTP', 'Kodau II', 1),
('fktp-lanud-iswahjudi-pringgodani', 'FKTP Lanud Iswahjudi / Pringgodani', 'FKTP', 'Kodau II', 1),
('fktp-lanud-abd-saleh-garuda', 'FKTP Lanud ABD Saleh / Garuda', 'FKTP', 'Kodau II', 1),
('fktp-lanud-sultan-hasanuddin-pataraja', 'FKTP Lanud Sultan Hasanuddin / Pataraja', 'FKTP', 'Kodau II', 1),
('fktp-lanud-sam-ratulangi', 'FKTP Lanud Sam Ratulangi', 'FKTP', 'Kodau II', 1),
('fktp-lanud-el-tari', 'FKTP Lanud El Tari', 'FKTP', 'Kodau II', 1),
('fktp-lanud-muljono', 'FKTP Lanud Muljono', 'FKTP', 'Kodau II', 1),
('fktp-lanud-dhomber-mulawarman', 'FKTP Lanud Dhomber / Mulawarman', 'FKTP', 'Kodau II', 1),
('fktp-lanud-i-gusti-ngurah-rai', 'FKTP Lanud I Gusti Ngurah Rai', 'FKTP', 'Kodau II', 1),
('fktp-lanud-anang-busra', 'FKTP Lanud Anang Busra', 'FKTP', 'Kodau II', 1),
('fktp-lanud-tgkh-zainudin-abdul-majid-kapitasi-non-kapitasi-yanmasum', 'FKTP Lanud TGKH Zainudin Abdul Majid: Kapitasi, Non Kapitasi, Yanmasum', 'FKTP', 'Kodau II', 1),
('fktp-lanud-sjamsudin-noor', 'FKTP Lanud Sjamsudin Noor', 'FKTP', 'Kodau II', 1),
('fktp-lanud-haluoleo', 'FKTP Lanud Haluoleo', 'FKTP', 'Kodau II', 1),
('fktp-lanud-jenderal-besar-soedirman', 'FKTP Lanud Jenderal Besar Soedirman', 'FKTP', 'Kodau II', 1),
('fktp-lanud-manuhua', 'FKTP Lanud Manuhua', 'FKTP', 'Kodau III', 1),
('fktp-lanud-silas-papare', 'FKTP Lanud Silas Papare', 'FKTP', 'Kodau III', 1),
('fktp-lanud-leo-wattimena', 'FKTP Lanud Leo Wattimena', 'FKTP', 'Kodau III', 1),
('fktp-lanud-pattimura', 'FKTP Lanud Pattimura', 'FKTP', 'Kodau III', 1),
('fktp-lanud-johanes-abraham-dimara', 'FKTP Lanud Johanes Abraham Dimara', 'FKTP', 'Kodau III', 1),
('fktp-lanud-dominicus-dumatubun', 'FKTP Lanud Dominicus Dumatubun', 'FKTP', 'Kodau III', 1),
('fktp-lanud-yohanis-kapiyau', 'FKTP Lanud Yohanis Kapiyau', 'FKTP', 'Kodau III', 1),
('fktp-denma-kodiklatau', 'FKTP Denma Kodiklatau', 'FKTP', 'Kodiklatau', 1),
('fktp-lanud-adisutjipto-cendrawasih', 'FKTP Lanud Adisutjipto / Cendrawasih', 'FKTP', 'Kodiklatau', 1),
('fktp-lanud-adi-soemarmo-colibri', 'FKTP Lanud Adi Soemarmo / Colibri', 'FKTP', 'Kodiklatau', 1),
('fktp-lanud-sulaiman', 'FKTP Lanud Sulaiman', 'FKTP', 'Kodiklatau', 1),
('fktp-wingdik-700-hanud', 'FKTP Wingdik 700/HANUD', 'FKTP', 'Kodiklatau', 1),
('fktp-wingdik-800-pasgat', 'FKTP Wingdik 800/PASGAT', 'FKTP', 'Kodiklatau', 1),
('fktp-denma-mabesau-yonkesau', 'FKTP Denma Mabesau / YONKESAU', 'FKTP', 'Balakpus', 1),
('fktp-denma-akademi-angkatan-udara', 'FKTP Denma Akademi Angkatan Udara', 'FKTP', 'Balakpus', 1),
('fktp-seskoau', 'FKTP Seskoau', 'FKTP', 'Balakpus', 1),
('fktp-rajawali-lakespra', 'FKTP Rajawali / Lakespra', 'FKTP', 'Balakpus', 1),
('fktp-dakota-lakespra', 'FKTP Dakota / Lakespra', 'FKTP', 'Balakpus', 1),
('fktp-lakesgilut-dirgantara', 'FKTP Lakesgilut / Dirgantara', 'FKTP', 'Balakpus', 1),
('fktp-lafiau', 'FKTP Lafiau', 'FKTP', 'Balakpus', 1),
('fktp-mako-korpaskgat', 'FKTP Mako Korpaskgat', 'FKTP', 'Korpaskgat', 1),
('fktp-sat-bravo-90-korpaskgat', 'FKTP Sat Bravo 90 Korpaskgat', 'FKTP', 'Korpaskgat', 1);

USE sifaskes;

-- Admin pusat (password default: AdminPusat!2026)
INSERT INTO users (facility_id, username, password_hash, role)
VALUES (
    NULL,
    'admin.pusat',
    '$2y$12$Gw1b1LRTEglmbftnWdPOO.gCEDRujKKtiL0zf.Dt/q.soLHwXMWV2',
    'admin_pusat'
);

-- Akun default untuk setiap fasilitas.
-- Password default rs_admin: AdminRS!2026
INSERT INTO users (facility_id, username, password_hash, role)
SELECT
    f.id,
    CONCAT(
        'admin.',
        CASE
            WHEN f.type = 'RSAU BLU' THEN 'blu'
            WHEN f.type = 'RSAU PNBP' THEN 'pnbp'
            ELSE 'fktp'
        END,
        '.',
        LPAD(f.id, 3, '0')
    ),
    '$2y$12$Y.FgjRI47H6Q7DG.ROV6Ke02j3Ocw.6aS3P5GUQWpxt6f9.b1LoYK',
    'rs_admin'
FROM facilities f;

-- Password default user_rs: UserRS!2026
INSERT INTO users (facility_id, username, password_hash, role)
SELECT
    f.id,
    CONCAT(
        'user.',
        CASE
            WHEN f.type = 'RSAU BLU' THEN 'blu'
            WHEN f.type = 'RSAU PNBP' THEN 'pnbp'
            ELSE 'fktp'
        END,
        '.',
        LPAD(f.id, 3, '0')
    ),
    '$2y$12$Z.jHwWGzjJTZ.jhTMXUk6eN8XfGWWvcQGuKKu/2YDJ.JSUte4o3Ke',
    'user_rs'
FROM facilities f;
